[project]
name = 'Datadao'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Datadao]
path = 'contracts/Datadao.clar'
clarity_version = 3
epoch = 3.1
[contracts.anonymous-tips]
path = 'contracts/anonymous-tips.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
